import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { CHASSIS, CHIPS, LOCATIONS, REGIONS, GAME_HOURS_PER_REAL_SECOND } from '../../src/systems/config'
import { calculateCompanyEconomy } from '../../src/systems/economy'
import { orderPrice, orderServerKit, mountChassisFromInventory, mountChipFromInventory } from '../../src/systems/procurement'
import { advanceSimulation, buyLocation, createInitialGame } from '../../src/systems/simulation'
import type { ActionResult, GameState } from '../../src/systems/types'

// This input is generated by executing the compiled, authoritative C++ domain
// immediately before these tests. It is not a handwritten JSON expectation.
const native = JSON.parse(readFileSync(`${process.env.MAI_TEST_OUTPUT ?? 'Unreal/Tests/.out'}/fixtures.json`, 'utf8')) as {
  quotes: Array<[number, number, number, number, number]>
  locations: Array<{ id: string; price: number; rent: number; rows: number; cols: number; watts: number }>
  garageCashAfterDelivery: number
  garageExpensesAfterDelivery: number
  garageElectricity: number
  garageMaintenance: number
  garageRent: number
  garageRevenue: number
  garageComputeMilli: number
}
const racks = ['rack-basic', 'rack-cooled', 'rack-enterprise'] as const
const chips = ['consumer-gpu', 'pro-gpu', 'accelerator', 'flagship'] as const
const unwrap = (result: ActionResult): GameState => {
  if (!result.ok) throw new Error(result.error)
  return result.state
}

describe('native C++ against unchanged TypeScript source', () => {
  it('covers all 336 item/channel/quantity quotes and all nine existing sites', () => {
    expect(native.quotes).toHaveLength(336)
    expect(new Set(native.quotes.map(row => row.slice(0, 4).join(':'))).size).toBe(336)
    expect(native.locations).toHaveLength(9)
  })
  it.each(native.quotes)('kind=%i item=%i channel=%i quantity=%i matches source price %i', (kind, item, channel, quantity, actual) => {
    const definition = kind === 0 ? CHASSIS[racks[item]] : CHIPS[chips[item]]
    expect(actual).toBe(orderPrice(definition.price, channel === 0 ? 'official' : 'grey', quantity))
  })
  it.each(native.locations)('preserves source location $id', actual => {
    const definition = [...LOCATIONS, ...REGIONS.flatMap(region => region.locations)].find(item => item.id === actual.id)
    expect(definition).toBeDefined()
    expect(actual).toMatchObject({
      id: definition!.id,
      price: definition!.price,
      rent: definition!.rentPerHour,
      rows: definition!.gridSize.rows,
      cols: definition!.gridSize.cols,
      watts: definition!.powerLimitKw * 1000,
    })
  })
  it('matches actual Garage purchase, clock, warehouse and cash posting', () => {
    const safe = () => 0.99
    const cell = { row: 0, col: 0 }
    let state = unwrap(buyLocation(createInitialGame(), 'garage'))
    state = unwrap(orderServerKit(state, { locationId: 'garage', chassis: 'rack-basic', chip: 'consumer-gpu', channel: 'official', qty: 1, targetCell: cell }))
    state = advanceSimulation(state, 6 / GAME_HOURS_PER_REAL_SECOND, safe)
    expect(state.cash).toBe(native.garageCashAfterDelivery)
    expect(state.totalExpenses).toBe(native.garageExpensesAfterDelivery)
    expect(state.orders).toHaveLength(0)
    state = unwrap(mountChassisFromInventory(state, 'garage', cell, 'rack-basic', safe))
    state = unwrap(mountChipFromInventory(state, 'garage', cell, 'consumer-gpu', safe))
    expect(state.cash).toBe(native.garageCashAfterDelivery)
    const economy = calculateCompanyEconomy(state)
    expect(economy.revenuePerHour).toBe(native.garageRevenue)
    expect(economy.profitPerHour).toBe(native.garageRevenue - native.garageElectricity - native.garageMaintenance - native.garageRent)
    expect(advanceSimulation(state, 1 / GAME_HOURS_PER_REAL_SECOND, safe).cash).toBe(state.cash + economy.profitPerHour)
  })
})
