#include "Campaign/MaiCampaign.h"
#include <algorithm>
#include <climits>
#include <fstream>
#include <iomanip>
#include <functional>
#include <iostream>
#include <sstream>
#include <stdexcept>

using namespace mai;
namespace {
int cases=0,checks=0,failures=0;
void check(bool value,const char* expression,int line) {++checks;if(!value) throw std::runtime_error(std::string(expression)+" at line "+std::to_string(line));}
#define CHECK(v) check((v),#v,__LINE__)
#define OK(v) do {auto r=(v); ++checks; if(!r.ok) throw std::runtime_error(std::string(#v)+": "+r.message);} while(false)
void Test(const char* name,const std::function<void()>& run) {++cases;try {run();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failures;std::cerr<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
void Ready(Campaign& c,const std::string& difficulty="Normal") {
    OK(c.CompleteLoad(c.View().loading.generation,true));OK(c.BeginNewGame());OK(c.ShowDifficulty());OK(c.ChooseDifficulty(difficulty));
    OK(c.PrologueAction("Test company"));OK(c.PrologueAction("budget"));OK(c.PrologueAction("accept-task"));
    CHECK(!c.CanPlay());OK(c.CompleteLoad(c.View().loading.generation,true));CHECK(c.CanPlay());
}
void Garage(Campaign& c) {
    Ready(c);OK(c.Core().BuyLocation("garage"));OK(c.Core().OrderKit("garage",0,0,Channel::Official,1,0));
    OK(c.AdvanceReal(6*Hour));OK(c.Core().MountChassis("garage",0,0));OK(c.Core().MountChip("garage",0,0));
    OK(c.BeginLoad(Screen::Gameplay,"garage"));OK(c.CompleteLoad(c.View().loading.generation,true));
}
void Fund(Campaign& c,Money amount=Dollars(100000)) {auto s=c.Core().View();s.cash=amount;OK(c.Core().Restore(s));}
void Manual(Campaign& c,const std::string& offer="official-text-10",bool good=true) {
    OK(c.BuyDataset(offer));const auto batch=c.View().inventory.sequence;OK(c.StartReview(batch,ReviewMethod::Manual));
    const auto id=c.View().reviewSequence;
    while(c.Review(id)->phase==ReviewPhase::Active) {const auto& r=*c.Review(id);const auto& item=r.items[r.decisions.size()];const int wrong=item.betterSide==2?0:1-item.betterSide;OK(c.AdvanceReal(Hour/60));OK(c.ChooseReview(id,good?item.betterSide:wrong));}
}
EndingMetrics Rich() {
    EndingMetrics m;m.cash=Dollars(2000000);m.value=Dollars(3000000);m.profitPerHour=Dollars(1000);m.modelMicroIQ=120000000;
    m.reputation=95;m.dataQualityBps=9500;m.successfulReviews=5;m.employeeCareBps=9000;m.difficulty="Normal";return m;
}
std::uint32_t Hash(const std::string& s) {std::uint32_t h=2166136261u;for(unsigned char b:s){h^=b;h*=16777619u;}return h;}
}
int main(int argc,char** argv) {
    if(argc==3 && std::string(argv[1])=="--export") {
        Campaign c;Garage(c);Manual(c);OK(c.StartTraining(1));OK(c.AdvanceReal(2*Hour));
        std::ofstream initial(std::string(argv[2])+"/campaign.save");initial<<c.Save();initial.close();
        OK(c.AdvanceReal(2*Hour));std::ofstream expected(std::string(argv[2])+"/expected.save");expected<<c.Save();
        return initial && expected?0:4;
    }
    if(argc==3 && std::string(argv[1])=="--resume") {
        std::ifstream file(argv[2]);std::ostringstream text;text<<file.rdbuf();Campaign c;auto r=c.Load(text.str());
        if(!r.ok) {std::cerr<<r.message;return 2;}r=c.AdvanceReal(2*Hour);if(!r.ok)return 3;std::cout<<c.Save();return 0;
    }
    Test("loading gates menus and rejects stale / failed callbacks",[]{Campaign c;CHECK(!c.CanPlay());CHECK(!c.BeginNewGame().ok);CHECK(!c.CompleteLoad(999,true).ok);OK(c.ReportLoading(c.View().loading.generation,-1,"Opening map"));CHECK(!c.CompleteLoad(c.View().loading.generation,false,"missing map").ok);CHECK(c.View().loading.phase==LoadPhase::Failed);CHECK(!c.BeginNewGame().ok);OK(c.BeginLoad(Screen::MainMenu));OK(c.CompleteLoad(c.View().loading.generation,true));CHECK(c.View().screen==Screen::MainMenu);});
    Test("new game difficulty and action-based prologue",[]{Campaign c;Ready(c);CHECK(c.Core().View().cash==Dollars(12000));CHECK(c.Core().View().reputation==50);CHECK(c.View().companyName=="Test company");CHECK(c.View().screen==Screen::CityMap);CHECK(c.View().decisions.size()>=4);});
    Test("all difficulty modifiers and Normal source parity",[]{for(const auto& name:{"Easy","Normal","Hard"}){Campaign c;Ready(c,name);CHECK(c.View().difficulty==name);CHECK(!c.ChooseDifficulty("Hard").ok);if(c.View().difficulty=="Easy"){CHECK(c.Core().View().cash==Dollars(18000));CHECK(c.Core().Definitions().defectPpm==40000);}if(c.View().difficulty=="Normal")CHECK(c.Core().Definitions().Fingerprint()==Catalog::Defaults().Fingerprint());if(c.View().difficulty=="Hard"){CHECK(c.Core().View().cash==Dollars(9600));CHECK(c.Core().Definitions().defectPpm==120000);}}});
    Test("difficulty survives reconstruction without re-applying capital",[]{Campaign a;Ready(a,"Hard");OK(a.Core().BuyLocation("garage"));Campaign b;OK(b.Load(a.Save()));CHECK(b.Save()==a.Save());CHECK(b.Core().View().cash==Dollars(8100));CHECK(b.Difficulty()->hiringBps==13000);});
    Test("invalid profile and skipped prologue rejected",[]{Campaign c;CHECK(!c.ChooseDifficulty("Normal").ok);OK(c.CompleteLoad(c.View().loading.generation,true));OK(c.BeginNewGame());OK(c.ShowDifficulty());CHECK(!c.ChooseDifficulty("Other").ok);OK(c.ChooseDifficulty("Normal"));CHECK(!c.PrologueAction("").ok);CHECK(!c.BeginLoad(Screen::CityMap).ok);CHECK(!c.BuyDataset("official-text-10").ok);});
    Test("purchased dataset enters unreviewed inventory with exact prorated price",[]{Campaign c;Ready(c);const auto cash=c.Core().View().cash;OK(c.BuyDataset("official-text-10"));const auto& b=c.View().inventory.batches.front();CHECK(b.status==DatasetStatus::Unreviewed);CHECK(b.volume==10);CHECK(b.cost==Dollars(1400));CHECK(c.Core().View().cash==cash-Dollars(1400));CHECK(!c.StartTraining(b.id).ok);});
    Test("bad / unaffordable dataset purchase is atomic",[]{Campaign c;Ready(c);const auto before=c.Save();CHECK(!c.BuyDataset("missing").ok);CHECK(!c.BuyDataset("official-text-100").ok);CHECK(c.Save()==before);});
    Test("Garage official kit, pause, warehouse and actual install",[]{Campaign c;Ready(c);OK(c.Core().BuyLocation("garage"));OK(c.Core().OrderKit("garage",0,0,Channel::Official,1,0));c.Core().SetPaused(true);const auto before=c.Save();OK(c.AdvanceReal(6*Hour));CHECK(c.Save()==before);c.Core().SetPaused(false);OK(c.AdvanceReal(6*Hour));CHECK(c.Core().View().orders.empty());OK(c.Core().MountChassis("garage",0,0));OK(c.Core().MountChip("garage",0,0));CHECK(c.Core().View().cash==Dollars(5220));});
    Test("manual review needs Garage and cannot train before verification",[]{Campaign c;Ready(c);OK(c.BuyDataset("official-text-10"));CHECK(!c.StartReview(1,ReviewMethod::Manual).ok);CHECK(!c.StartReview(1,ReviewMethod::Human).ok);CHECK(!c.StartReview(1,ReviewMethod::AI).ok);CHECK(!c.StartTraining(1).ok);});
    Test("manual text branch four stages and result reward",[]{Campaign c;Garage(c);Manual(c);const auto& r=c.View().reviews.front();CHECK(r.items.size()==4);CHECK(r.decisions.size()==4);for(const auto& i:r.items)CHECK(i.type==DataType::Text);CHECK(c.Batch(1)->status==DatasetStatus::Verified);CHECK(c.Batch(1)->quality.scoreBps==9900);CHECK(r.elapsed==4*Hour/60);CHECK(r.reward==2);CHECK(!c.ChooseReview(r.id,0).ok);});
    Test("manual image branch uses explicit cards, not nonexistent photos",[]{Campaign c;Garage(c);Manual(c,"official-image-10");for(const auto& i:c.View().reviews.front().items){CHECK(i.type==DataType::Image);CHECK(i.left.find("CARD:")!=std::string::npos);CHECK(i.leftAsset.empty());}CHECK(c.Batch(1)->status==DatasetStatus::Verified);});
    Test("mixed branch alternates text and image",[]{Campaign c;Garage(c);Manual(c,"official-mixed-10");int text=0,image=0;for(const auto& i:c.View().reviews.front().items){text+=i.type==DataType::Text;image+=i.type==DataType::Image;}CHECK(text==2 && image==2);});
    Test("manual 3-5 stage profiles are enforced",[]{for(int steps:{3,4,5}){auto r=CampaignRules::Defaults();r.manualSteps=steps;Campaign c(Catalog::Defaults(),r);Garage(c);Manual(c);CHECK(c.View().reviews.front().decisions.size()==static_cast<std::size_t>(steps));}auto r=CampaignRules::Defaults();std::string e;r.manualSteps=6;CHECK(!r.Valid(e));});
    Test("poor manual choices reject batch and cannot mint rewards again",[]{Campaign c;Garage(c);Manual(c,"official-text-10",false);CHECK(c.Batch(1)->status==DatasetStatus::Rejected);CHECK(c.View().reward==-2);CHECK(!c.StartTraining(1).ok);const auto before=c.Save();CHECK(!c.StartReview(1,ReviewMethod::Manual).ok);CHECK(c.Save()==before);});
    Test("mid-review restart retains exact sampled cards and decisions",[]{Campaign a;Garage(a);OK(a.BuyDataset("official-mixed-10"));OK(a.StartReview(1,ReviewMethod::Manual));OK(a.ChooseReview(1,a.Review(1)->items[0].betterSide));Campaign b;OK(b.Load(a.Save()));CHECK(a.Save()==b.Save());for(int i=1;i<4;++i){OK(a.ChooseReview(1,a.Review(1)->items[static_cast<std::size_t>(i)].betterSide));OK(b.ChooseReview(1,b.Review(1)->items[static_cast<std::size_t>(i)].betterSide));}CHECK(a.Save()==b.Save());});
    Test("human review is paid, queued, capacity-limited and imperfect",[]{Campaign c;Garage(c);Fund(c);OK(c.HireSpecialist());OK(c.BuyDataset("official-text-10"));OK(c.BuyDataset("official-image-10"));const auto cash=c.Core().View().cash;OK(c.StartReview(1,ReviewMethod::Human));OK(c.StartReview(2,ReviewMethod::Human));CHECK(c.Core().View().cash==cash-2*c.View().specialists[0].batchFee);OK(c.AdvanceReal(Hour/60));CHECK(c.Review(1)->phase==ReviewPhase::Active);CHECK(c.Review(2)->phase==ReviewPhase::Queued);OK(c.AdvanceReal(Hour));CHECK(c.Review(2)->phase==ReviewPhase::Complete);CHECK(c.View().specialists[0].fatigueBps>0);CHECK(c.Batch(1)->quality.scoreBps<10000);});
    Test("AI reviewer requires compute and creates systematic bias",[]{Campaign c;Ready(c);CHECK(!c.CreateAIReviewer().ok);Campaign g;Garage(g);Fund(g);OK(g.CreateAIReviewer());OK(g.BuyDataset("official-image-10"));OK(g.StartReview(1,ReviewMethod::AI));CHECK(g.AvailableTrainingCompute()==500);OK(g.AdvanceReal(Hour/5));CHECK(g.Review(1)->phase==ReviewPhase::Complete);CHECK(g.Batch(1)->quality.scoreBps<9900);const auto bias=g.View().ai.biasBps;OK(g.ImproveAIReviewer());CHECK(g.View().ai.biasBps<bias);});
    Test("AI review stalls without working servers",[]{Campaign c;Garage(c);Fund(c);OK(c.CreateAIReviewer());OK(c.BuyDataset("official-text-10"));OK(c.StartReview(1,ReviewMethod::AI));OK(c.Core().FailChip("garage",0));const auto remaining=c.Review(1)->remainingMicro;OK(c.AdvanceReal(Hour));CHECK(c.Review(1)->remainingMicro==remaining);});
    Test("AI completion cannot double-spend server compute in the same quantum",[]{auto r=CampaignRules::Defaults();r.aiVolumePerComputeHour=1000;Campaign c(Catalog::Defaults(),r);Garage(c);Fund(c);Manual(c);OK(c.CreateAIReviewer());OK(c.BuyDataset("official-text-10"));OK(c.StartReview(2,ReviewMethod::AI));OK(c.StartTraining(1));OK(c.AdvanceReal(2*Hour/60));CHECK(c.Review(2)->phase==ReviewPhase::Complete);CHECK(10000000-c.View().training[0].remainingMicro==33333);});
    Test("micro repayments cannot erase competitor dependence",[]{Campaign c;Ready(c);OK(c.Borrow(Dollars(1000)));const auto before=c.View().dependencyBps;OK(c.Repay(1));CHECK(c.View().dependencyBps>=before-1);CHECK(c.View().debt==Dollars(1000)-1);});
    Test("loading preserves a player's pause even at time zero",[]{Campaign c;Ready(c);c.Core().SetPaused(true);OK(c.BeginLoad(Screen::CityMap));OK(c.CompleteLoad(c.View().loading.generation,true));CHECK(c.Core().View().paused);});
    Test("regulator thresholds are driven by profiles",[]{auto r=CampaignRules::Defaults();auto m=Rich();m.legalBps=8500;m.ignoredWarnings=2;CHECK(EndingEvaluator::Evaluate(m,r.endings).kind!=EndingKind::Regulator);r.endings[0].regulatorMinLegalBps=8000;r.endings[0].regulatorMinIgnoredWarnings=2;CHECK(EndingEvaluator::Evaluate(m,r.endings).kind==EndingKind::Regulator);});
    Test("dataset quality changes expected training gain",[]{Campaign a;Garage(a);Manual(a);OK(a.StartTraining(1));const auto high=a.View().training[0].expectedGainMicroIQ;Campaign b;Garage(b);OK(b.BuyDataset("official-text-10"));OK(b.StartReview(1,ReviewMethod::Manual));for(int i=0;i<4;++i){const auto correct=b.Review(1)->items[static_cast<std::size_t>(i)].betterSide;const int wrong=correct==2?0:1-correct;OK(b.ChooseReview(1,i==0?wrong:correct));}OK(b.StartTraining(1));CHECK(b.View().training[0].expectedGainMicroIQ<high);});
    Test("training job pause and global pause preserve progress",[]{Campaign c;Garage(c);Manual(c);OK(c.StartTraining(1));OK(c.PauseTraining(true));const auto remaining=c.View().training[0].remainingMicro;OK(c.AdvanceReal(Hour));CHECK(c.View().training[0].remainingMicro==remaining);OK(c.PauseTraining(false));c.Core().SetPaused(true);const auto before=c.Save();OK(c.AdvanceReal(Hour));CHECK(c.Save()==before);});
    Test("training stalls after hardware failure without losing reviewed batch",[]{Campaign c;Garage(c);Manual(c);OK(c.StartTraining(1));OK(c.Core().FailChip("garage",0));const auto remaining=c.View().training[0].remainingMicro;OK(c.AdvanceReal(Hour));CHECK(c.View().training[0].remainingMicro==remaining);CHECK(c.Batch(1)->status==DatasetStatus::Training);});
    Test("complete Normal vertical through save reload and ending evaluation",[]{Campaign a;Garage(a);Manual(a);OK(a.StartTraining(1));OK(a.AdvanceReal(2*Hour));Campaign b;OK(b.Load(a.Save()));CHECK(a.Save()==b.Save());OK(a.AdvanceReal(3*Hour));OK(b.AdvanceReal(3*Hour));CHECK(a.Save()==b.Save());CHECK(b.Batch(1)->status==DatasetStatus::Trained);CHECK(b.View().modelMicroIQ>0);OK(b.EvaluateEnding());CHECK(b.View().ending.kind==EndingKind::None);CHECK(b.Core().View().cash>0);std::cout<<"VERTICAL_NORMAL cash="<<b.Core().View().cash<<" IQmicro="<<b.View().modelMicroIQ<<" manualDecisions="<<b.Review(1)->decisions.size()<<'\n';});
    Test("fixed step invariance including reviews and persistence",[]{Campaign a;Garage(a);Fund(a);OK(a.HireSpecialist());OK(a.BuyDataset("official-text-10"));OK(a.StartReview(1,ReviewMethod::Human));Campaign b;OK(b.Load(a.Save()));OK(a.AdvanceReal(Hour));for(int i=0;i<600;++i)OK(b.AdvanceReal(Hour/600));CHECK(a.Save()==b.Save());});
    Test("schema corruption is atomic and unsupported versions are rejected",[]{Campaign c;Garage(c);const auto before=c.Save();CHECK(!c.Load(before+"garbage").ok);CHECK(c.Save()==before);auto wrong=before;wrong.replace(13,1,"9");CHECK(!c.Load(wrong).ok);CHECK(c.Save()==before);});
    Test("legacy native save migration preserves orders and cash",[]{Simulation old;OK(old.BuyLocation("garage"));OK(old.OrderKit("garage",0,0,Channel::Grey,1,0));Campaign c;OK(c.Load(old.Save()));CHECK(c.View().difficulty=="Normal");CHECK(c.Core().Save()==old.Save());CHECK(c.Core().View().orders.size()==2);CHECK(c.View().screen==Screen::CityMap);});
    Test("campaign v1 migrates first and last viewed screens",[]{Campaign c;Garage(c);const auto save=c.Save();const auto pos=save.find('\n');std::istringstream body(save.substr(pos+1));std::string core;int screen=0,first=0,last=0,resume=0;body>>std::quoted(core)>>screen>>first>>last>>resume;std::string rest((std::istreambuf_iterator<char>(body)),{});for(int i=0;i<5;++i){while(!rest.empty()&&(rest.back()==' '||rest.back()=='\n')) rest.pop_back();while(!rest.empty()&&rest.back()!=' '&&rest.back()!='\n') rest.pop_back();}std::ostringstream v1body;v1body<<std::quoted(core)<<' '<<screen<<rest;std::ostringstream wire;wire<<"MAI-CAMPAIGN 1 "<<Catalog::Defaults().Fingerprint()<<' '<<CampaignRules::Defaults().Fingerprint()<<' '<<Hash(v1body.str())<<'\n'<<v1body.str();Campaign loaded;OK(loaded.Load(wire.str()));CHECK(loaded.View().firstScreen==Screen::Loading);CHECK(loaded.View().lastScreen==Screen::Gameplay);});
    Test("pending loader state survives save without becoming ready",[]{Campaign a;Ready(a);OK(a.Core().BuyLocation("garage"));OK(a.BeginLoad(Screen::Gameplay,"garage"));OK(a.ReportLoading(a.View().loading.generation,4500,"Loading required room assets"));Campaign b;OK(b.Load(a.Save()));CHECK(a.Save()==b.Save());CHECK(!b.CanPlay());CHECK(b.View().loading.progressBps==4500);});
    Test("acquisition offer requires explicit acceptance",[]{auto m=Rich();const auto rules=CampaignRules::Defaults();auto e=EndingEvaluator::Evaluate(m,rules.endings);CHECK(e.kind==EndingKind::Acquisition);CHECK(e.offerOnly);m.saleAccepted=true;e=EndingEvaluator::Evaluate(m,rules.endings);CHECK(!e.offerOnly);CHECK(e.deal==Dollars(3750000));CHECK(e.line.find("Elon Max")!=std::string::npos);});
    Test("independent global success",[]{auto m=Rich();m.saleDeclined=true;m.international=true;const auto e=EndingEvaluator::Evaluate(m,CampaignRules::Defaults().endings);CHECK(e.kind==EndingKind::Independent);});
    Test("open model is an explicit decision with data and investor limits",[]{auto m=Rich();m.openChosen=true;CHECK(EndingEvaluator::Evaluate(m,CampaignRules::Defaults().endings).kind==EndingKind::OpenModel);m.dependencyBps=9000;CHECK(EndingEvaluator::Evaluate(m,CampaignRules::Defaults().endings).kind==EndingKind::None);});
    Test("bankruptcy overrides sale and disallows return to final save",[]{auto m=Rich();m.bankrupt=true;auto e=EndingEvaluator::Evaluate(m,CampaignRules::Defaults().endings);CHECK(e.kind==EndingKind::Bankruptcy);CHECK(!e.allowReturnToSave);});
    Test("regulator overrides bankruptcy and every positive ending",[]{auto m=Rich();m.bankrupt=true;m.legalBps=9500;m.ignoredWarnings=3;m.saleAccepted=true;auto e=EndingEvaluator::Evaluate(m,CampaignRules::Defaults().endings);CHECK(e.kind==EndingKind::Regulator);auto profiles=CampaignRules::Defaults().endings;std::reverse(profiles.begin(),profiles.end());CHECK(EndingEvaluator::Evaluate(m,profiles).kind==e.kind);});
    Test("all five ending conditions produce one deterministic result",[]{for(auto kind:{EndingKind::Acquisition,EndingKind::Independent,EndingKind::OpenModel,EndingKind::Bankruptcy,EndingKind::Regulator}){auto m=Rich();m.saleAccepted=kind==EndingKind::Acquisition;m.saleDeclined=kind==EndingKind::Independent;m.international=m.saleDeclined;m.openChosen=kind==EndingKind::OpenModel;m.bankrupt=kind==EndingKind::Bankruptcy;if(kind==EndingKind::Regulator){m.legalBps=9500;m.ignoredWarnings=3;}CHECK(EndingEvaluator::Evaluate(m,CampaignRules::Defaults().endings).kind==kind);}});
    Test("actual ending flow uses test-only thresholds, not production shortcuts",[]{auto rules=CampaignRules::Defaults();for(auto& e:rules.endings)if(e.kind==EndingKind::OpenModel){e.minModelMicroIQ=1;e.minReputation=50;e.minDataQualityBps=6000;}Campaign c(Catalog::Defaults(),rules);Garage(c);Manual(c);OK(c.StartTraining(1));OK(c.AdvanceReal(5*Hour));OK(c.ChooseEnding(EndingKind::OpenModel));CHECK(c.View().screen==Screen::Ending);CHECK(c.Core().View().ended);CHECK(!c.BuyDataset("official-text-10").ok);Campaign loaded(Catalog::Defaults(),rules);OK(loaded.Load(c.Save()));CHECK(loaded.Save()==c.Save());CHECK(loaded.View().ending.metrics.difficulty=="Normal");CHECK(!loaded.View().ending.decisions.empty());OK(loaded.BeginNewGame());CHECK(loaded.View().screen==Screen::NewGame);CHECK(!loaded.Core().View().ended);});
    Test("Elon Max remains a fictional character with an honest portrait slot",[]{const auto c=CampaignRules::Defaults().buyer;CHECK(c.fictional);CHECK(c.name=="Elon Max");CHECK(c.biography.find("Fictional")!=std::string::npos);CHECK(c.portraitSlot.find("Fictional")!=std::string::npos);CHECK(c.fallback.find("pending")!=std::string::npos);});
    Test("Garage interaction points and distance boundaries",[]{const auto profiles=InteriorProfiles();CHECK(profiles.size()==5);CHECK(profiles.front().walkable);CHECK(profiles.front().points.size()==5);CHECK(!profiles[1].walkable);CHECK(WithinInteractionRange(100,0,0,200));CHECK(WithinInteractionRange(200,0,0,200));CHECK(!WithinInteractionRange(201,0,0,200));CHECK(!WithinInteractionRange(INT_MAX,INT_MAX,0,200));Campaign c;Garage(c);OK(c.TalkToGarageNpc());});
    Test("hard hire cost and shared court modifier are preserved on reload",[]{Campaign c;Ready(c,"Hard");const auto cash=c.Core().View().cash;OK(c.HireSpecialist());CHECK(c.Core().View().cash==cash-Dollars(650));CHECK(c.Core().Definitions().regions[0].courtBps==16000);Campaign b;OK(b.Load(c.Save()));CHECK(b.Save()==c.Save());});
    Test("debt is not revenue and repayment cannot mint cash",[]{Campaign c;Ready(c);const auto revenue=c.Core().View().revenue;OK(c.Borrow(Dollars(5000)));CHECK(c.View().debt==Dollars(5000));CHECK(c.Core().View().revenue==revenue);OK(c.Repay(Dollars(5000)));CHECK(c.View().debt==0);const auto before=c.Save();CHECK(!c.Repay(Unit).ok);CHECK(c.Save()==before);});
    Test("new company loading does not advance operating time",[]{Campaign c;Garage(c);const auto now=c.Core().View().now;OK(c.BeginLoad(Screen::CityMap));OK(c.AdvanceReal(24*Hour));CHECK(c.Core().View().now==now);});
    std::cout<<"NATIVE_CAMPAIGN_RESULT cases="<<cases<<" assertions="<<checks<<" failures="<<failures<<'\n';return failures?1:0;
}
