#include "Core/MaiDomain.h"
#include "test_harness.h"
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>
using namespace mai;
namespace {
void Fund(Simulation& sim,Money amount=Dollars(1000000)) {auto s=sim.View();s.cash=amount;OK(sim.Restore(s));}
void Install(Simulation& sim,const std::string& id="garage",int rack=0,int chip=0) {
    OK(sim.BuyLocation(id));OK(sim.OrderKit(id,rack,chip,Channel::Official,1,0));OK(sim.AdvanceReal(12*Hour));OK(sim.MountChassis(id,0,rack));OK(sim.MountChip(id,0,chip));
}
Catalog Experimental() {
    auto c=Catalog::Defaults();auto& x=c.extensions;x.nuclearConfigured=true;x.nuclearPrice=Dollars(1000);x.nuclearTariffBps=7500;
    x.auctionConfigured=true;x.auctionReserve=Dollars(4800);x.bidIncrement=Dollars(100);x.rivalBudget=Dollars(4900);x.rivalInterval=Hour/2;
    auto& r=c.regions[static_cast<std::size_t>(c.RegionIndex("greenhaven"))];r.configured=true;r.unlockPrice=Dollars(100);r.tariffBps=8000;
    auto& l=c.locations[static_cast<std::size_t>(c.LocationIndex("greenhaven-site"))];l.configured=true;l.price=Dollars(1500);l.rent=Dollars(80);l.rows=3;l.cols=3;l.powerWatts=3000;
    return c; // TEST FIXTURE ONLY; not production balance.
}
void Fixtures() {
    const auto c=Catalog::Defaults();std::cout<<"{\"quotes\":[";bool first=true;
    for(int k=0;k<2;++k) for(int item=0;item<(k==0?3:4);++item) for(int ch=0;ch<2;++ch) for(int q=1;q<=24;++q) {
        if(!first)std::cout<<',';first=false;const auto base=k==0?c.chassis[static_cast<std::size_t>(item)].price:c.chips[static_cast<std::size_t>(item)].price;
        std::cout<<"["<<k<<','<<item<<','<<ch<<','<<q<<','<<Simulation::OrderPrice(base,static_cast<Channel>(ch),q)/Unit<<"]";
    }
    std::cout<<"],\"locations\":[";first=true;
    for(const auto& l:c.locations) if(l.configured) {if(!first)std::cout<<',';first=false;std::cout<<"{\"id\":\""<<l.id<<"\",\"price\":"<<l.price/Unit<<",\"rent\":"<<l.rent/Unit<<",\"rows\":"<<l.rows<<",\"cols\":"<<l.cols<<",\"watts\":"<<l.powerWatts<<"}";}
    Simulation sim(c,42);sim.BuyLocation("garage");sim.OrderKit("garage",0,0,Channel::Official,1,0);sim.AdvanceReal(6*Hour);
    std::cout<<"],\"garageCashAfterDelivery\":"<<sim.View().cash/Unit<<",\"garageExpensesAfterDelivery\":"<<sim.View().expenses/Unit;
    sim.MountChassis("garage",0,0);sim.MountChip("garage",0,0);const auto e=sim.Economy();
    std::cout<<",\"garageElectricity\":"<<e.electricity/Unit<<",\"garageMaintenance\":"<<e.maintenance/Unit<<",\"garageRent\":"<<e.rent/Unit<<",\"garageRevenue\":"<<e.revenue/Unit<<",\"garageComputeMilli\":"<<e.computeMilli<<",\"schema\":1}\n";
}
}
int main(int argc,char** argv) {
    if(argc==2 && std::string(argv[1])=="--fixtures") {Fixtures();return 0;}
    const auto test=[](const char* name,auto fn){++cases;const int before=failures;fn();std::cout<<(failures==before?"PASS ":"FAIL ")<<name<<'\n';};
    test("initial state and home statuses",[]{Simulation s;CHECK(s.View().cash==Dollars(12000));CHECK(s.View().now==0);CHECK(s.LocationStatus("garage")==Status::Available);CHECK(s.LocationStatus("campus")==Status::Available);CHECK(s.LocationStatus("overseas-west")==Status::Locked);CHECK(s.LocationStatus("missing")==Status::Locked);CHECK(s.View().locations.size()==10);});
    test("browser prices and quantity rejection",[]{CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Official,1)==Dollars(3200));CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Grey,1)==Dollars(2200));CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Official,2)==Dollars(6080));CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Grey,2)==Dollars(4180));CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Official,5)==Dollars(12800));CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Grey,24)==Dollars(42240));CHECK(Simulation::OrderPrice(Dollars(5000),Channel::Grey,3)==Dollars(14850));CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Official,0)==-1);CHECK(Simulation::OrderPrice(Dollars(2000),Channel::Official,25)==-1);});
    test("buy once and no invented progression",[]{Simulation s;OK(s.BuyLocation("garage"));CHECK(s.View().cash==Dollars(10500));CHECK(s.LocationStatus("garage")==Status::Owned);const auto before=s.Save();CHECK(!s.BuyLocation("garage").ok);CHECK(s.Save()==before);});
    test("atomic insufficient kit leaves both orders and cash unchanged",[]{Simulation s;OK(s.BuyLocation("garage"));Fund(s,Dollars(3000));const auto before=s.Save();CHECK(!s.OrderKit("garage",0,0,Channel::Official,1,0).ok);CHECK(s.Save()==before);});
    test("official delivery and mounting flow",[]{Simulation s(Catalog::Defaults(),42);OK(s.BuyLocation("garage"));OK(s.OrderKit("garage",0,0,Channel::Official,1,0));CHECK(s.View().cash==Dollars(5700));CHECK(!s.MountChassis("garage",0,0).ok);OK(s.AdvanceReal(6*Hour-1));CHECK(s.View().orders.size()==2);OK(s.AdvanceReal(1));CHECK(s.View().orders.empty());CHECK(s.View().cash==Dollars(5220));CHECK(s.View().locations[0].chassisStock[0].total==1);const auto rng=s.View().equipmentRng;OK(s.MountChassis("garage",0,0));OK(s.MountChip("garage",0,0));CHECK(s.View().cash==Dollars(5220));CHECK(s.View().equipmentRng==rng);CHECK(s.Economy().computeMilli==1000);CHECK(s.Economy().Expenses()==Dollars(206));CHECK(s.Economy().revenue==0);});
    test("bulk kit and independent channel ETAs",[]{Simulation s;Fund(s);OK(s.BuyLocation("campus"));const auto cash=s.View().cash;OK(s.OrderKit("campus",0,0,Channel::Grey,3,0));CHECK(s.View().cash==cash-Dollars(8910));OK(s.AdvanceReal(2*Hour));CHECK(s.View().locations[4].chipStock[0].grey==3);CHECK(s.View().locations[4].chassisStock[0].grey==3);});
    test("pause freezes all deliveries and 3x time",[]{Simulation s;OK(s.BuyLocation("garage"));OK(s.OrderKit("garage",0,0,Channel::Official,1,0));s.SetPaused(true);const auto before=s.Save();OK(s.AdvanceReal(100*Hour));CHECK(s.Save()==before);s.SetPaused(false);OK(s.SetSpeed(3));OK(s.AdvanceReal(2*Hour));CHECK(s.View().now==6*Hour);CHECK(s.View().orders.empty());CHECK(!s.SetSpeed(2).ok);});
    test("grey chassis defect and disposal",[]{Simulation s(Catalog::Defaults(),1);OK(s.BuyLocation("garage"));OK(s.OrderItem("garage",Kind::Chassis,0,Channel::Grey,1));OK(s.AdvanceReal(2*Hour));const auto cash=s.View().cash;OK(s.MountChassis("garage",0,0));CHECK(s.View().locations[0].slots[0].chassis==-1);CHECK(s.View().cash==cash-Dollars(150));CHECK(s.View().locations[0].chassisStock[0].total==0);});
    test("official stock is consumed before grey without a roll",[]{Simulation s;OK(s.BuyLocation("garage"));auto snapshot=s.View();snapshot.locations[0].chassisStock[0]={2,1};OK(s.Restore(snapshot));const auto seed=s.View().equipmentRng;OK(s.MountChassis("garage",0,0));CHECK(s.View().equipmentRng==seed);CHECK(s.View().locations[0].chassisStock[0].total==1);CHECK(s.View().locations[0].chassisStock[0].grey==1);});
    test("power refusal is atomic and consumes no RNG",[]{Simulation s;Fund(s);Install(s);auto st=s.View();st.locations[0].chassisStock[0]={1,0};st.locations[0].chipStock[0]={1,1};OK(s.Restore(st));OK(s.MountChassis("garage",1,0));const auto before=s.Save();CHECK(!s.MountChip("garage",1,0).ok);CHECK(s.Save()==before);});
    test("compatible upgrade retains server id and old chip",[]{Simulation s;Fund(s);Install(s);auto st=s.View();st.locations[0].chipStock[1]={1,0};OK(s.Restore(st));const auto cash=s.View().cash;const auto id=s.View().locations[0].slots[0].serverId;OK(s.MountChip("garage",0,1));CHECK(s.View().cash==cash);CHECK(s.View().locations[0].slots[0].serverId==id);CHECK(s.View().locations[0].chipStock[0].total==1);CHECK(s.View().locations[0].slots[0].chassis==0);});
    test("defective upgrade returns old chip and retains chassis",[]{Simulation s;Fund(s);Install(s);auto st=s.View();st.equipmentRng=1;st.locations[0].chipStock[1]={1,1};OK(s.Restore(st));const auto cash=s.View().cash;OK(s.MountChip("garage",0,1));CHECK(s.View().locations[0].slots[0].chip==-1);CHECK(s.View().locations[0].slots[0].chassis==0);CHECK(s.View().locations[0].chipStock[0].total==1);CHECK(s.View().cash==cash-Dollars(900));});
    test("incompatible chip does not remove stock",[]{Simulation s;Fund(s);Install(s);auto st=s.View();st.locations[0].chipStock[3]={1,0};OK(s.Restore(st));const auto before=s.Save();CHECK(!s.MountChip("garage",0,3).ok);CHECK(s.Save()==before);});
    test("shared failure retains rack and charges once",[]{Simulation s;Fund(s);Install(s);const auto cash=s.View().cash;OK(s.FailChip("garage",0));CHECK(s.View().cash==cash-Dollars(300));CHECK(s.View().locations[0].slots[0].chassis==0);CHECK(!s.FailChip("garage",0).ok);});
    test("daily audience at hour 16, not a compute cash shortcut",[]{Simulation s(Catalog::Defaults(),42);Install(s);OK(s.AdvanceReal(4*Hour));CHECK(s.View().now==16*Hour);CHECK(s.View().usersMicro==82500000);CHECK(s.Economy().revenue==Dollars(132));});
    test("fixed point substep invariance",[]{Simulation a(Catalog::Defaults(),42);Install(a);Simulation b;OK(b.Load(a.Save()));OK(a.AdvanceReal(Hour/2));for(int i=0;i<600;++i)OK(b.AdvanceReal(Hour/1200));CHECK(a.Save()==b.Save());});
    test("pending delivery survives process-style reconstruction",[]{Simulation a;OK(a.BuyLocation("garage"));OK(a.OrderKit("garage",0,0,Channel::Official,1,0));OK(a.AdvanceReal(2*Hour));Simulation b;OK(b.Load(a.Save()));CHECK(a.Save()==b.Save());OK(a.AdvanceReal(4*Hour));OK(b.AdvanceReal(4*Hour));CHECK(a.Save()==b.Save());});
    test("installed servers and money survive load",[]{Simulation a;Fund(a);Install(a);Simulation b;OK(b.Load(a.Save()));CHECK(a.Save()==b.Save());CHECK(b.View().locations[0].slots[0].chip==0);});
    test("corrupt and unsupported saves cannot mutate live state",[]{Simulation s;const auto before=s.Save();CHECK(!s.Load(before+"damage").ok);CHECK(s.Save()==before);auto corrupt=s.View();corrupt.locations[0].chipStock[0]={1,2};CHECK(!s.Restore(corrupt).ok);CHECK(s.Save()==before);auto changed=Catalog::Defaults();changed.chips[0].price+=Unit;Simulation other(changed);CHECK(!other.Load(before).ok);});
    test("board restrictions block orders but not stocked mounting",[]{Simulation s;OK(s.BuyLocation("garage"));auto st=s.View();st.restrictedUntil=Hour;st.locations[0].chassisStock[0]={1,0};OK(s.Restore(st));CHECK(!s.OrderItem("garage",Kind::Chip,0,Channel::Official,1).ok);OK(s.MountChassis("garage",0,0));});
    test("auction winner uses regular delivery without a second purchase",[]{Simulation s(Experimental(),42);OK(s.BuyLocation("garage"));OK(s.StartAuction("garage"));OK(s.Bid(Dollars(5000)));OK(s.AdvanceReal(2*Hour));CHECK(s.View().auction.phase==AuctionPhase::Won);CHECK(s.View().orders.size()==2);CHECK(s.View().cash==Dollars(5340));CHECK(s.View().capex==Dollars(6500));OK(s.AdvanceReal(6*Hour));CHECK(s.View().locations[0].chipStock[0].total==1);});
    test("auction loss refunds escrow and respects rival budget",[]{Simulation s(Experimental(),42);OK(s.BuyLocation("garage"));OK(s.StartAuction("garage"));CHECK(!s.Bid(Dollars(999999)).ok);OK(s.Bid(Dollars(4800)));OK(s.AdvanceReal(Hour/2));CHECK(!s.View().auction.playerLeading);CHECK(s.View().auction.escrow==0);CHECK(s.View().cash==Dollars(10460));OK(s.AdvanceReal(3*Hour/2));CHECK(s.View().auction.phase==AuctionPhase::Lost);CHECK(s.View().orders.empty());CHECK(s.View().capex==Dollars(1500));});
    test("auction replay survives save with escrow and RNG",[]{Simulation a(Experimental(),42);OK(a.BuyLocation("garage"));OK(a.StartAuction("garage"));OK(a.Bid(Dollars(4800)));Simulation b(Experimental());OK(b.Load(a.Save()));OK(a.AdvanceReal(2*Hour));OK(b.AdvanceReal(2*Hour));CHECK(a.Save()==b.Save());});
    test("nuclear tariff applies only to real consumption, once",[]{Simulation s(Experimental(),42);Fund(s);Install(s);const auto revenue=s.Economy().revenue;CHECK(s.Economy().electricity==Dollars(36));OK(s.BuyNuclear());CHECK(s.Economy().electricity==Dollars(27));CHECK(s.Economy().revenue==revenue);CHECK(!s.BuyNuclear().ok);Simulation b(Experimental());OK(b.Load(s.Save()));CHECK(b.View().nuclearOwned);});
    test("unconfigured extensions cannot create free purchases",[]{Simulation s;CHECK(!s.BuyNuclear().ok);CHECK(!s.UnlockRegion("greenhaven").ok);OK(s.BuyLocation("garage"));CHECK(!s.StartAuction("garage").ok);});
    test("Greenhaven uses shared regions, tariffs and court risk",[]{Simulation s(Experimental());Fund(s);CHECK(s.LocationStatus("greenhaven-site")==Status::Locked);OK(s.UnlockRegion("greenhaven"));CHECK(s.LocationStatus("greenhaven-site")==Status::Available);OK(s.SwitchRegion("greenhaven"));Install(s,"greenhaven-site");CHECK(s.Economy().electricity==28800000);auto st=s.View();st.dirtyHistory=true;OK(s.Restore(st));CHECK(s.CourtRiskPpm()==50000);OK(s.UnlockRegion("overseas"));OK(s.BuyLocation("overseas-west"));CHECK(s.CourtRiskPpm()==75000);Simulation b(Experimental());OK(b.Load(s.Save()));CHECK(b.View().activeRegion=="greenhaven");});
    test("NPC entry, phone, reaction, cooldown and re-entry",[]{NpcState n;CHECK(!UpdateProximity(n,false,0,10,40));CHECK(UpdateProximity(n,true,0,10,40));CHECK(n.mode==NpcMode::PhoneCall);CHECK(!UpdateProximity(n,true,10,10,40));CHECK(n.mode==NpcMode::React);CHECK(!UpdateProximity(n,true,20,10,40));CHECK(n.mode==NpcMode::Idle);CHECK(!UpdateProximity(n,false,30,10,40));CHECK(!UpdateProximity(n,true,31,10,40));CHECK(!UpdateProximity(n,false,41,10,40));CHECK(UpdateProximity(n,true,42,10,40));CHECK(n.eventCount==2);});
    test("NPC and deterministic seeds survive save",[]{Simulation a;CHECK(a.Proximity(true,10,40));Simulation b;OK(b.Load(a.Save()));CHECK(a.Save()==b.Save());CHECK(!b.Proximity(true,10,40));CHECK(b.View().npc.eventCount==1);});
    RunCampaignTests();
    std::cout<<"NATIVE_DOMAIN_RESULT cases="<<cases<<" assertions="<<assertions<<" failures="<<failures<<"\n";
    return failures==0?0:1;
}
