#pragma once
#include <string>
#include <unordered_map>

// Central user-visible copy. Gameplay rules live in domain classes; this table
// is only display text so a later localization pass can replace English.
namespace mai {
inline const char* Loc(const char* id) {
    static const std::unordered_map<std::string, const char*> k = {
        {"app.title", "MAKE YOUR AI"},
        {"app.subtitle", "SOURCE_SCAFFOLD / portable vertical slice"},
        {"screen.loading", "Loading"},
        {"screen.main-menu", "Main Menu"},
        {"screen.new-game", "New Game"},
        {"screen.difficulty", "Difficulty"},
        {"screen.prologue", "Prologue"},
        {"screen.city-map", "City Map"},
        {"screen.gameplay", "Garage"},
        {"screen.training", "Training"},
        {"screen.ending", "Ending"},
        {"screen.results", "Results"},
        {"screen.settings", "Settings"},
        {"menu.new-game", "New Game"},
        {"menu.load-game", "Load Game"},
        {"menu.settings", "Settings"},
        {"menu.quit", "Quit"},
        {"menu.back", "Back"},
        {"menu.no-save", "No save in this slot. New Game creates a company; existing slots stay untouched."},
        {"load.status", "Preparing required assets"},
        {"load.retry", "Retry"},
        {"load.cancel", "Cancel load"},
        {"load.failed", "Required asset or scene failed to load"},
        {"load.not-cancellable", "This load cannot be cancelled"},
        {"difficulty.easy", "Easy"},
        {"difficulty.normal", "Normal"},
        {"difficulty.hard", "Hard"},
        {"difficulty.easy.blurb", "More starting capital, slower defects, longer insolvency grace. Procurement prices stay at the base catalog."},
        {"difficulty.normal.blurb", "Base catalog: $12,000, source delivery prices, 8% grey defect, 48-hour insolvency grace."},
        {"difficulty.hard.blurb", "Less capital, higher defect and court risk, shorter insolvency grace. Base prices unchanged."},
        {"difficulty.locked", "Difficulty is locked for the lifetime of this company"},
        {"prologue.name-prompt", "Name the company (one line, 1-80 bytes)."},
        {"prologue.budget-prompt", "Inspect the starter budget. Equipment, licensed data and specialists all cost money."},
        {"prologue.task-prompt", "First task: buy Garage, install a server, review a dataset, then train."},
        {"prologue.accept", "Accept first task"},
        {"ending.offer", "Elon Max has made an acquisition offer"},
        {"ending.elon-max.letter", "Letter from Elon Max, fictional founder of Maximal Teapots:\n\nYour model boiled the market. We launch luxury kettles into orbit, not cars. The remade face on this letter is the character who writes it — not a documentary photograph.\n\n— Elon Max"},
        {"ending.accept", "Accept Elon Max offer"},
        {"ending.decline", "Decline and remain independent"},
        {"ending.open", "Publish the model"},
        {"ending.continue", "View results"},
        {"results.new-game", "New Game"},
        {"results.load", "Load Game"},
        {"review.left", "Choose left"},
        {"review.right", "Choose right"},
        {"review.both-bad", "Both are bad"},
        {"review.skip", "Skip sample"},
        {"review.cancel", "Cancel manual review"},
        {"review.hire", "Hire specialist"},
        {"review.ai-create", "Create AI reviewer"},
        {"review.ai-improve", "Improve AI reviewer"},
        {"review.start-manual", "Start manual review at the Garage desk"},
        {"review.start-human", "Assign specialist review"},
        {"review.start-ai", "Assign AI review"},
        {"inventory.unreviewed", "Unreviewed"},
        {"inventory.verified", "Verified"},
        {"inventory.rejected", "Rejected"},
        {"walk.hint", "WASD move / E interact / hints appear within 1.5 m"},
        {"walk.exit", "Return to city map"},
        {"walk.desk", "Dataset review desk"},
        {"walk.warehouse", "Warehouse"},
        {"walk.terminal", "Location terminal"},
        {"walk.advisor", "Advisor"},
        {"settings.text-scale", "Text scale"},
        {"settings.reduced-motion", "Reduced motion"},
        {"hud.pause", "Pause"},
        {"hud.resume", "Resume"},
        {"hud.city", "City map"},
        {"hud.enter-garage", "Walk Garage"},
        {"hud.save", "Save company"},
        {"hud.load", "Load company"},
        {"character.elon-max.notice", "Elon Max is a fictional parody character. The ending portrait is an author-supplied remade likeness, not a documentary photograph of a living public figure."},
        {"status.source-only", "UE compilation, Editor, visual and gameplay verification: NOT VERIFIED."},
        {"status.proxy-world", "Graybox layout is a test stand-in, not imported CityV4."},
        {"placeholder.elon-max", "DEV PLACEHOLDER until Editor import: remade source is Content/Source/Portraits/elon_max_remade.jpg. UE texture T_ElonMax_Fictional is not imported."}
    };
    const auto it = k.find(id);
    return it == k.end() ? id : it->second;
}
inline std::string LocStr(const char* id) { return Loc(id); }
} // namespace mai
