from pathlib import Path

def edit(file,a,b):
 p=Path(file);s=p.read_text(encoding='utf-8-sig');assert a in s,(file,a);p.write_text(s.replace(a,b),encoding='utf8')
edit('src/store/gameStore.ts','    purchaseOffice: () => void\n  purchaseCityTower:',"    purchaseOffice: () => apply(buyOffice(get().game), 'Головной офис куплен. Теперь можно войти.'),\n    purchaseCityTower:")
edit('src/persistence/saves.ts','    ...(game.cityProperties !== undefined ?', '    ...(officeOwned === undefined ? {} : { officeOwned }),\n    ...(game.cityProperties !== undefined ?')
p=Path('src/ui/App.tsx');s=p.read_text(encoding='utf-8-sig');s="import { OFFICE_PRICE } from '../systems/city'\n"+s;s=s.replace("| 'restore' | null","| 'restore' | 'office-purchase' | null").replace("onClick={() => goScreen('office')}","onClick={() => state.game.officeOwned ? goScreen('office') : openDialog('office-purchase')}").replace("{screen === 'office' &&", "{screen === 'office' && state.game.officeOwned &&")
s=s.replace('{state.notice &&','''{dialog === 'office-purchase' && <Modal title="Головной офис" onClose={() => setDialog(null)}><span className="card-caption">Недвижимость компании</span><p className="card-description">Собственный ресепшен, переговорная и рабочее место руководителя. Офис покупается отдельно от серверных площадок.</p><div className="office-purchase-visual"><span>NEURON</span><strong>HEADQUARTERS</strong><small>Ресепшен · переговорная · кабинет</small></div><button className="primary-button wide" disabled={!state.ready || state.game.cash < OFFICE_PRICE || !!state.game.ending} onClick={() => { state.purchaseOffice(); if (useGameStore.getState().game.officeOwned) { setDialog(null); goScreen('office') } }}>Купить офис<span>{money(OFFICE_PRICE)}</span></button></Modal>}
    {state.notice &&''');p.write_text(s,encoding='utf8')
p=Path('src/ui/OfficeScreen.tsx');s=p.read_text(encoding='utf-8-sig').replace('    if (!host.current) return','    if (!host.current || !game.officeOwned) return').replace('  }, [])','  }, [game.officeOwned])').replace('  return <main','  if (!game.officeOwned) return null\n  return <main');p.write_text(s,encoding='utf8')
p=Path('src/render/interiorLayout.ts');s=p.read_text().replace('1.25','1.3').replace('2.8','2.25');p.write_text(s,encoding='utf8')
p=Path('src/render/InteriorScene.ts');s=p.read_text(encoding='utf-8-sig').replace('object.scale.set(1, .55, 1)','object.scale.setScalar(1)').replace('// Keep even enterprise racks below the 22-degree sightline to the next row.','// Preserve full authored rack proportions.').replace('        child.userData.cell = item.gridPosition',"        child.userData.cell = item.gridPosition\n        if (child.name === 'compute_modules' && !('chip' in item)) child.visible = false").replace("'#b9e68c'","item.chip === 'flagship' ? '#c498ed' : '#75d6b9'").replace('Math.max(7, this.grid.cols * 1.25 + 3)','Math.max(6.6, this.grid.cols * 1.3 + 3.1)').replace('(this.grid.rows - 1) * ROW_SPACING + 4','(this.grid.rows - 1) * ROW_SPACING + 3.6').replace('(roomWidth + 2) / 2','(roomWidth + depth * .18 + 1.5) / 2').replace('new THREE.Vector3(0, 30 * Math.tan(ELEVATION), 30)','new THREE.Vector3(6, 30 * Math.tan(ELEVATION), 29.4)').replace('light.position.set(-5, 12, 7)','light.position.set(-5, 9, 5)').replace('new THREE.DirectionalLight(0xffe3ba, 2.5)','new THREE.DirectionalLight(0xffe3ba, 2.2)');p.write_text(s,encoding='utf8')
